// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCuarnGiQ02WqA3pDmCfLdM8wsE6kyQSY',
    appId: '1:481289247031:web:7da051ac674cccb8dde2b2',
    messagingSenderId: '481289247031',
    projectId: 'aplicacion-movil-1ea44',
    authDomain: 'aplicacion-movil-1ea44.firebaseapp.com',
    storageBucket: 'aplicacion-movil-1ea44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKpMoqd34aJulo5pqcQmXE3pQfTCtVZ7Y',
    appId: '1:481289247031:android:d650e1a3fdcba3e7dde2b2',
    messagingSenderId: '481289247031',
    projectId: 'aplicacion-movil-1ea44',
    storageBucket: 'aplicacion-movil-1ea44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXEGACg5dsSm_v90Ll2cFYGB1cv8r8aU4',
    appId: '1:481289247031:ios:9aeb4c1ca9cbe3cbdde2b2',
    messagingSenderId: '481289247031',
    projectId: 'aplicacion-movil-1ea44',
    storageBucket: 'aplicacion-movil-1ea44.firebasestorage.app',
    iosBundleId: 'com.example.loveuts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXEGACg5dsSm_v90Ll2cFYGB1cv8r8aU4',
    appId: '1:481289247031:ios:9aeb4c1ca9cbe3cbdde2b2',
    messagingSenderId: '481289247031',
    projectId: 'aplicacion-movil-1ea44',
    storageBucket: 'aplicacion-movil-1ea44.firebasestorage.app',
    iosBundleId: 'com.example.loveuts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCuarnGiQ02WqA3pDmCfLdM8wsE6kyQSY',
    appId: '1:481289247031:web:27a68eeeda03edd1dde2b2',
    messagingSenderId: '481289247031',
    projectId: 'aplicacion-movil-1ea44',
    authDomain: 'aplicacion-movil-1ea44.firebaseapp.com',
    storageBucket: 'aplicacion-movil-1ea44.firebasestorage.app',
  );
}
