// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFU6G2dboAvb-Yf70duoPwj54k1tnRbzA',
    appId: '1:828583960275:web:7a031193ed21011a0b7e26',
    messagingSenderId: '828583960275',
    projectId: 'loveuts-7a90a',
    authDomain: 'loveuts-7a90a.firebaseapp.com',
    storageBucket: 'loveuts-7a90a.firebasestorage.app',
    measurementId: 'G-DV8DP9255G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm-EvXojHGFdF4riOUAjaOFqMfKqo94jw',
    appId: '1:828583960275:android:c1be8fe350ee37820b7e26',
    messagingSenderId: '828583960275',
    projectId: 'loveuts-7a90a',
    storageBucket: 'loveuts-7a90a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCReHPuUN6nxB0lmK49cRSpGqNKBA_IvzQ',
    appId: '1:828583960275:ios:d11260c00ab5ee370b7e26',
    messagingSenderId: '828583960275',
    projectId: 'loveuts-7a90a',
    storageBucket: 'loveuts-7a90a.firebasestorage.app',
    iosBundleId: 'com.example.loveuts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCReHPuUN6nxB0lmK49cRSpGqNKBA_IvzQ',
    appId: '1:828583960275:ios:d11260c00ab5ee370b7e26',
    messagingSenderId: '828583960275',
    projectId: 'loveuts-7a90a',
    storageBucket: 'loveuts-7a90a.firebasestorage.app',
    iosBundleId: 'com.example.loveuts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFU6G2dboAvb-Yf70duoPwj54k1tnRbzA',
    appId: '1:828583960275:web:647e0185678de6940b7e26',
    messagingSenderId: '828583960275',
    projectId: 'loveuts-7a90a',
    authDomain: 'loveuts-7a90a.firebaseapp.com',
    storageBucket: 'loveuts-7a90a.firebasestorage.app',
    measurementId: 'G-QCXF6S7VC7',
  );

}